config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :reviews
  resources :book_shelves do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :reviews
  has_many :books_and_book_shelves
  has_many :book_shelves,  -> { distinct } , through: :books_and_book_shelves

  def add_book(book, book_shelf)
    book_shelf.books << book
  end

  def remove_book(book, book_shelf)
    book.book_shelves.delete(book_shelf)
  end

end

app/models/book_shelf.rb
class BookShelf < ApplicationRecord

  has_many :reviews
  has_many :books_and_book_shelves
  has_many :books,  -> { distinct }, through: :books_and_book_shelves



end

app/models/books_and_book_shelf.rb
class BooksAndBookShelf < ApplicationRecord

  belongs_to :book_shelf
  belongs_to :book

end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :book, required: false
  belongs_to :book_shelf, required: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/book_shelves_controller.rb
class BookShelvesController < ApplicationController
  before_action :set_book_shelf_and_books, only: [:show, :edit, :update, :destroy]

  def index
    @book_shelves = BookShelf.all
    @books = Book.all
  end
  def show
  end
  def new
    @book_shelf = BookShelf.new
  end
  def create
    @book_shelf = BookShelf.new(book_shelf_params)
    if @book_shelf.save
      redirect_to book_shelves_path, notice: 'saved.'
    else
      render "new"
    end
  end

  private
    def set_book_shelf_and_books
      @book_shelf = BookShelf.find(params[:id])
      @books = Book.all
    end

    def book_shelf_params
      params[:book_shelf].permit!
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book_shelf
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = @book_shelf.books.order('id DESC')
  end
  def show
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'saved.'
    else
      render "new"
    end
  end
  def edit
  end
  def update
  end

  private
    def set_book_shelf
      @book_shelf = BookShelf.find(params[:id])
    end

    def set_book
      @book = @book_shelf.books.find(params[:id])
    end

    def book_params
      params[:book].permit!
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/book_shelves/index.html.haml
=link_to "new book shelf", new_book_shelf_path
-@book_shelves.each do |book_shelf|
  %h3=link_to "Book Shelf Desc: #{book_shelf.description}", book_shelf_path(book_shelf)
  -book_shelf.books.each do |book|
    %ul
      %li
        =link_to "Title: #{book.name}", book_shelf_book_path(book_shelf, book)
      %li
        ="Author: #{book.author_name}"

app/views/book_shelves/new.html.haml
=form_for @book_shelf do |f|
  =f.text_field :description
  =f.submit

app/views/book_shelves/show.html.haml
%h1 Set Books
%ul
  -@book_shelf.books.each do |book|
    %li=book.name
    %button
      text
      -book.remove_book(book, @book_shelf)
%h1 Unset Books
%ul
  -@books.each do |book|
    %li=link_to book.name, book_shelf_book_path(@book_shelf, book)
    %button
      text
      -book.add_book(book, @book_shelf)

app/views/books/index.html.haml
=link_to "New Book", new_book_path
-@books.each do |book|
  =book.name

app/views/books/new.html.haml
=form_for @book do |f|
  =f.text_field :name
  =f.text_field :author_name
  =f.submit

app/views/home/index.html.haml
=link_to "Book Shelves", book_shelves_path
=link_to "books", books_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>